# Use this file to define settings related to application configuration
# Use this file to define settings that are UNIVERSAL (not specific to any environment)
# Information in this file will be PUBLIC (this file is tracked in git)
# Declarations in config/settings.local.yml override declarations in this file

frontend:
  # With trailing slash
  url: http://dp.la/
relative_url_root: /primary-source-sets
