# Use this file to define settings related to application configuration
# Use this file to define settings that are UNIVERSAL (not specific to any environment)
# Information in this file will be PUBLIC (this file is tracked in git)
# Declarations in config/settings.local.yml override declarations in this file

frontend:
  url: //example.com/

wordpress:
 url: //example.com/

exhibtions:
  url: //exmaple.com/

api:
  url: //example.com/
  key: CHANGEME

app_scheme: 'http://'
# app_host may include port
app_host: 'localhost:3000'

relative_url_root: /

aws:
  region: 'CHANGEME'
  access_key_id: 'CHANGEME'
  secret_access_key: 'CHANGEME'
  s3_upload_bucket: 'CHANGEME'
  s3_destination_bucket: 'CHANGEME'
  cloudfront_domain: 'CHANGEME'


widgets:
  # Urls for social icons
  social_icons:
    facebook: https://www.facebook.com/example
    twitter: https://twitter.com/example
    tumblr: http://example.tumblr.com/
    rss: http://example.org/info/feed


contact_email: email@example.com

# default http response headers
http_headers:
  x_frame_options: 'SAMEORIGIN'
