---

- hosts: all
  sudo: yes
  tasks:
    - name: Upgrade o/s packages
      apt: upgrade=safe update_cache=yes
    - name: Ensure that necessary packages are installed
      apt: >-
        pkg="{{ item }}" state=present
      with_items:
        - curl
        - unzip
        - git
        - g++
        - sqlite3
        - libsqlite3-dev
        - postgresql-common
        - libpq-dev
        - build-essential
        - libfontconfig1-dev
        - memcached

- hosts: all
  # do as "vagrant" user
  sudo: no
  tasks:
    - name: Ensure that Ruby packages and tools are installed
      script: files/install_ruby_tools.sh 2.1.3
